CREATE PROCEDURE [dbo].[ExecuteQueuedSQL]
AS

SET NOCOUNT ON
SET DATEFIRST 1

DECLARE curQueued CURSOR FORWARD_ONLY READ_ONLY FOR
	SELECT SQLToExecute FROM QueuedSQL

DECLARE @SQL		VARCHAR(8000)

OPEN curQueued
FETCH NEXT FROM curQueued INTO @SQL

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @SQL
	EXEC (@SQL)

	FETCH NEXT FROM curQueued INTO @SQL

END

CLOSE curQueued
DEALLOCATE curQueued

DELETE FROM QueuedSQL
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[ExecuteQueuedSQL] TO PUBLIC
    AS [dbo];

