CREATE PROCEDURE dbo.NIS_UPDATE_USER_LOGGING_DETAILS
(
	@USERID				AS INT,
	@LASTWEBSITELOGINDATE		AS DATETIME,
	@LASTWEBSITELOGINIPADDRESS	AS VARCHAR(255)
)
AS
UPDATE Users
SET LastWebsiteLoginDate = @LASTWEBSITELOGINDATE, LastWebsiteLoginIPAddress = @LASTWEBSITELOGINIPADDRESS
WHERE ID = @USERID

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[NIS_UPDATE_USER_LOGGING_DETAILS] TO PUBLIC
    AS [dbo];

