CREATE TABLE [dbo].[MasterDates] (
    [ID]     INT      IDENTITY (1, 1) NOT NULL,
    [EDISID] INT      NOT NULL,
    [Date]   DATETIME NOT NULL,
    CONSTRAINT [PK_MasterDates] PRIMARY KEY CLUSTERED ([EDISID] ASC, [Date] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MasterDates_Sites] FOREIGN KEY ([EDISID]) REFERENCES [dbo].[Sites] ([EDISID]) ON DELETE CASCADE,
    CONSTRAINT [UX_MasterDates_ID] UNIQUE NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_MasterDates_Date]
    ON [dbo].[MasterDates]([Date] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_MasterDates_EDISID]
    ON [dbo].[MasterDates]([EDISID] ASC) WITH (FILLFACTOR = 90);

