CREATE TABLE [dbo].[Owners] (
    [ID]                                        INT           IDENTITY (1, 1) NOT NULL,
    [Name]                                      VARCHAR (255) NULL,
    [Address1]                                  VARCHAR (255) DEFAULT ('') NOT NULL,
    [Address2]                                  VARCHAR (255) DEFAULT ('') NOT NULL,
    [Address3]                                  VARCHAR (255) DEFAULT ('') NOT NULL,
    [Address4]                                  VARCHAR (255) DEFAULT ('') NOT NULL,
    [Postcode]                                  VARCHAR (9)   DEFAULT ('') NOT NULL,
    [ContactName]                               VARCHAR (255) DEFAULT ('') NOT NULL,
    [SendScorecardEmail]                        BIT           DEFAULT ((0)) NOT NULL,
    [POSYieldCashValue]                         MONEY         DEFAULT ((0)) NOT NULL,
    [CleaningCashValue]                         MONEY         DEFAULT ((0)) NOT NULL,
    [PouringYieldCashValue]                     MONEY         DEFAULT ((0)) NOT NULL,
    [TargetPouringYieldPercent]                 INT           DEFAULT ((0)) NOT NULL,
    [TargetTillYieldPercent]                    INT           DEFAULT ((0)) NOT NULL,
    [ScorecardFromEmailAddress]                 VARCHAR (100) NULL,
    [ThroughputLowValue]                        INT           DEFAULT ((20)) NOT NULL,
    [ThroughputAmberTaps]                       INT           DEFAULT ((1)) NOT NULL,
    [ThroughputRedTaps]                         INT           DEFAULT ((2)) NOT NULL,
    [PouringYieldAmberPercentFromTarget]        INT           DEFAULT ((2)) NOT NULL,
    [PouringYieldRedPercentFromTarget]          INT           DEFAULT ((3)) NOT NULL,
    [TillYieldAmberPercentFromTarget]           INT           DEFAULT ((2)) NOT NULL,
    [TillYieldRedPercentFromTarget]             INT           DEFAULT ((3)) NOT NULL,
    [TemperatureOutOfSpecPercentTarget]         INT           DEFAULT ((0)) NOT NULL,
    [TemperatureAmberPercentTarget]             INT           DEFAULT ((20)) NOT NULL,
    [TemperatureRedPercentTarget]               INT           DEFAULT ((30)) NOT NULL,
    [CleaningAmberPercentTarget]                INT           DEFAULT ((20)) NOT NULL,
    [CleaningRedPercentTarget]                  INT           DEFAULT ((30)) NOT NULL,
    [DailyScorecardSubject]                     VARCHAR (MAX) NULL,
    [DailyScorecardHTML]                        VARCHAR (MAX) NULL,
    [DispenseMonitoringDataHTML]                VARCHAR (MAX) NULL,
    [DispenseMonitoringDataSubject]             VARCHAR (MAX) NULL,
    [PDFReportPackHTML]                         VARCHAR (MAX) NULL,
    [PDFReportPackSubject]                      VARCHAR (MAX) NULL,
    [ProductTempAlarmsEnabled]                  BIT           DEFAULT ((0)) NOT NULL,
    [ProductTempHighPercentThreshold]           INT           DEFAULT ((25)) NOT NULL,
    [CleaningAlarmsEnabled]                     BIT           DEFAULT ((0)) NOT NULL,
    [OverallYieldAlarmsEnabled]                 BIT           DEFAULT ((0)) NOT NULL,
    [OverallYieldLowPercentThreshold]           INT           DEFAULT ((98)) NOT NULL,
    [PouringYieldAlarmsEnabled]                 BIT           DEFAULT ((0)) NOT NULL,
    [PouringYieldLowPercentThreshold]           INT           DEFAULT ((102)) NOT NULL,
    [RetailYieldAlarmsEnabled]                  BIT           DEFAULT ((0)) NOT NULL,
    [RetailYieldLowPercentThreshold]            INT           DEFAULT ((99)) NOT NULL,
    [ThroughputAlarmsEnabled]                   BIT           DEFAULT ((0)) NOT NULL,
    [ThroughputMinThreshold]                    INT           DEFAULT ((20)) NOT NULL,
    [OutOfHoursDispenseAlarmsEnabled]           BIT           DEFAULT ((0)) NOT NULL,
    [OutOfHoursDispenseMinThreshold]            FLOAT (53)    CONSTRAINT [DF_OutOfHoursDispenseMinThreshold] DEFAULT ((1)) NOT NULL,
    [NoDataAlarmsEnabled]                       BIT           DEFAULT ((0)) NOT NULL,
    [ReportingFirstDayOfWeek]                   INT           DEFAULT ((1)) NOT NULL,
    [ReportingShowWorstYieldFirst]              BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowOverallYieldPercent]          BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowOverallYieldCashValue]        BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowOverallYield]                 BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowOverallYieldAverage]          BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowOverallYieldAverageCashValue] BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowRetailYieldPercent]           BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowRetailYieldCashValue]         BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowPouringYieldPercent]          BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowCleaningLoss]                 BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowCleaningLinesOverdue]         BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowNumberOfAlarms]               BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowNumberOfExceptions]           BIT           DEFAULT ((1)) NOT NULL,
    [ReportingShowNumberOfEmailsSent]           BIT           DEFAULT ((1)) NOT NULL,
    [UseExceptionReporting]                     BIT           DEFAULT ((0)) NOT NULL,
    [ExceptionEmailHeaderHTML]                  VARCHAR (MAX) NULL,
    [ExceptionEmailFooterHTML]                  VARCHAR (MAX) NULL,
    [ExceptionEmailCleaningHTML]                VARCHAR (MAX) NULL,
    [ExceptionEmailProductTempHTML]             VARCHAR (MAX) NULL,
    [ExceptionEmailOverallYieldHTML]            VARCHAR (MAX) NULL,
    [ExceptionEmailCellarTempHTML]              VARCHAR (MAX) NULL,
    [ExceptionEmailCoolerTempHTML]              VARCHAR (MAX) NULL,
    [ExceptionEmailOutOfHoursDispenseHTML]      VARCHAR (MAX) NULL,
    [ExceptionEmailPouringYieldHTML]            VARCHAR (MAX) NULL,
    [ExceptionEmailRetailYieldHTML]             VARCHAR (MAX) NULL,
    [ExceptionEmailThroughputHTML]              VARCHAR (MAX) NULL,
    [ExceptionEmailNoDataHTML]                  VARCHAR (MAX) NULL,
    [WeeklySiteReportHTML]                      VARCHAR (MAX) NULL,
    [WeeklyExecReportHTML]                      VARCHAR (MAX) NULL,
    [WelcomeEmailHTML]                          VARCHAR (MAX) NULL,
    [ExceptionEmailSubject]                     VARCHAR (MAX) NULL,
    [CellarAlarmEmailSubject]                   VARCHAR (MAX) NULL,
    [CoolerAlarmEmailSubject]                   VARCHAR (MAX) NULL,
    [NoDataAlarmEmailSubject]                   VARCHAR (MAX) NULL,
    [WeeklySiteReportSubject]                   VARCHAR (MAX) NULL,
    [WeeklyExecReportSubject]                   VARCHAR (MAX) NULL,
    [WelcomeEmailSubject]                       VARCHAR (MAX) NULL,
    [ReportingShowDispenseViaUncleanLines]      BIT           DEFAULT ((1)) NOT NULL,
    [IncludeCleaningWasteInOverallYield]        BIT           DEFAULT ((0)) NOT NULL,
    [CleaningLowVolumeThreshold]                FLOAT (53)    DEFAULT ((1)) NOT NULL,
    [AllowSiteExceptionConfigurationOverride]   BIT           DEFAULT ((0)) NOT NULL,
    [OverallYieldHighVolumeThreshold]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RetailYieldHighVolumeThreshold]            FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AutoSendExceptions]                        BIT           DEFAULT ((0)) NOT NULL,
    [ReportingShowRetailYield]                  BIT           DEFAULT ((0)) NOT NULL,
    [ReportingShowPouringYield]                 BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Owners] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

