CREATE TABLE [dbo].[PeriodCacheVarianceInternalStaging] (
    [PeriodCacheVarianceInternalStagingId] INT             IDENTITY (1, 1) NOT NULL,
    [WeekCommencing]                       DATE            NULL,
    [OrganisationID]                       SMALLINT        NULL,
    [SiteID]                               SMALLINT        NULL,
    [ProductName]                          NVARCHAR (100)  NULL,
    [SiteName]                             NVARCHAR (200)  NULL,
    [neoProductId]                         SMALLINT        DEFAULT ((0)) NULL,
    [CategoryID]                           SMALLINT        DEFAULT ((0)) NULL,
    [ContainerType]                        NVARCHAR (16)   DEFAULT ('None') NULL,
    [CategoryDescription]                  NVARCHAR (100)  DEFAULT ('None') NULL,
    [ThresholdReferenceData]               NVARCHAR (100)  NULL,
    [StockDate]                            DATETIME2 (3)   NULL,
    [Stock]                                DECIMAL (18, 8) NULL,
    [DeliveredDate]                        DATE            NULL,
    [Delivered]                            DECIMAL (18, 8) NOT NULL,
    [Dispensed]                            DECIMAL (18, 8) NOT NULL,
    [StockAdjustedDispensed]               DECIMAL (18, 8) NULL,
    [Variance]                             DECIMAL (18, 8) NOT NULL,
    [DeliveredBeforeStocktake]             DECIMAL (18, 8) NULL,
    [DeliveredAfterStocktake]              DECIMAL (18, 8) NULL,
    [StockAdjustedDelivered]               DECIMAL (18, 8) NOT NULL,
    [StockAdjustedVariance]                DECIMAL (18, 8) NOT NULL,
    [DispensedMinusFive]                   DECIMAL (18, 8) NOT NULL,
    [StockAdjustedDispenseMinusFive]       DECIMAL (18, 8) NOT NULL,
    [varianceMinusFive]                    DECIMAL (18, 8) NOT NULL,
    [stockAdjustedVarianceMinusFive]       DECIMAL (18, 8) NOT NULL,
    [trafficLightStatus]                   NVARCHAR (16)   NULL,
    [DATE]                                 DATE            NULL,
    [OldWorldProductId]                    SMALLINT        NULL,
    [IsTied]                               BIT             NOT NULL,
    PRIMARY KEY CLUSTERED ([PeriodCacheVarianceInternalStagingId] ASC)
);

