CREATE TABLE [dbo].[PeriodCacheCalls] (
    [DatabaseID]                                     INT          NOT NULL,
    [CustomerName]                                   VARCHAR (50) NOT NULL,
    [Date]                                           DATETIME     NOT NULL,
    [DMSSites]                                       INT          NOT NULL,
    [IDraughtSites]                                  INT          NOT NULL,
    [DMSCompletedCalls]                              INT          NOT NULL,
    [IDraughtCompletedCalls]                         INT          NOT NULL,
    [DMSCompletedCallsInSLA]                         INT          NOT NULL,
    [IDraughtCompletedCallsInSLA]                    INT          NOT NULL,
    [DMSCompletedCallsOutSLA]                        INT          NOT NULL,
    [IDraughtCompletedCallsOutSLA]                   INT          NOT NULL,
    [SNACallsTotal]                                  INT          NOT NULL,
    [SNACallsInSLA]                                  INT          NOT NULL,
    [SNACallsOutSLA]                                 INT          NOT NULL,
    [CallsOutstanding]                               INT          NOT NULL,
    [CallsOpen]                                      INT          NOT NULL,
    [AvgDaysFaultToApproved]                         FLOAT (53)   NOT NULL,
    [AvgDaysApprovedToCompleted]                     FLOAT (53)   NOT NULL,
    [SitesWithZeroCalls]                             INT          NOT NULL,
    [SitesWithOverFiveCalls]                         INT          NOT NULL,
    [CallsOnHold]                                    INT          NOT NULL,
    [DMSCallsOnHold]                                 INT          NOT NULL,
    [IDraughtCallsOnHold]                            INT          NOT NULL,
    [CallsOnHoldBrulinesIssue]                       INT          NOT NULL,
    [CallsOnHoldClientIssue]                         INT          NOT NULL,
    [FlowmetersInstalled]                            INT          NOT NULL,
    [DMSFlowmetersInstalledTotal]                    INT          NOT NULL,
    [IDraughtFlowmetersInstalledTotal]               INT          NOT NULL,
    [DMSFlowmetersInstalledInPeriod]                 INT          NOT NULL,
    [IDraughtFlowmetersInstalledInPeriod]            INT          NOT NULL,
    [FlowmetersCleaned]                              INT          NOT NULL,
    [CallsCompleted]                                 INT          NOT NULL,
    [CallsRaised]                                    INT          DEFAULT ((0)) NOT NULL,
    [CallsCancelled]                                 INT          DEFAULT ((0)) NOT NULL,
    [CallsAborted]                                   INT          DEFAULT ((0)) NOT NULL,
    [AvgDMSDaysApprovedToCompleted]                  FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [AvgIDraughtDaysApprovedToCompleted]             FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CalFailureNoProduct]                            INT          DEFAULT ((0)) NOT NULL,
    [CalFailureFobbing]                              INT          DEFAULT ((0)) NOT NULL,
    [CalFailureDispenseIssue]                        INT          DEFAULT ((0)) NOT NULL,
    [CallsCompletedLast6Periods]                     INT          DEFAULT ((0)) NOT NULL,
    [AvgDMSDaysApprovedToCompletedLast6Periods]      FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [AvgIDraughtDaysApprovedToCompletedLast6Periods] FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CallsInProgress]                                INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenAvgDays]                               FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CallsInProgressAvgDays]                         FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CallsOpenOutsideSLA]                            INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenOutsideSLAAvgDays]                     FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CallsOpenOutsideSLADMS]                         INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenOutsideSLADMSAvgDays]                  FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CallsOpenOutsideSLAIDraught]                    INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenOutsideSLAIDraughtAvgDays]             FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [DMSSitesWithZeroCalls]                          INT          DEFAULT ((0)) NOT NULL,
    [IDraughtSitesWithZeroCalls]                     INT          DEFAULT ((0)) NOT NULL,
    [DMSSitesWithOverFiveCalls]                      INT          DEFAULT ((0)) NOT NULL,
    [IDraughtSitesWithOverFiveCalls]                 INT          DEFAULT ((0)) NOT NULL,
    [DMSCallsCompletedPrevious6Periods]              INT          DEFAULT ((0)) NOT NULL,
    [IDraughtCallsCompletedPrevious6Periods]         INT          DEFAULT ((0)) NOT NULL,
    [SNACallsDMSTotal]                               INT          DEFAULT ((0)) NOT NULL,
    [SNACallsDMSInSLA]                               INT          DEFAULT ((0)) NOT NULL,
    [SNACallsDMSOutSLA]                              INT          DEFAULT ((0)) NOT NULL,
    [SNACallsIDraughtTotal]                          INT          DEFAULT ((0)) NOT NULL,
    [SNACallsIDraughtInSLA]                          INT          DEFAULT ((0)) NOT NULL,
    [SNACallsIDraughtOutSLA]                         INT          DEFAULT ((0)) NOT NULL,
    [CallsRaisedDMS]                                 INT          DEFAULT ((0)) NOT NULL,
    [CallsRaisedIDraught]                            INT          DEFAULT ((0)) NOT NULL,
    [CallsOutstandingDMS]                            INT          DEFAULT ((0)) NOT NULL,
    [CallsOutstandingIDraught]                       INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenDMS]                                   INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenIDraught]                              INT          DEFAULT ((0)) NOT NULL,
    [CallsInProgressDMS]                             INT          DEFAULT ((0)) NOT NULL,
    [CallsInProgressIDraught]                        INT          DEFAULT ((0)) NOT NULL,
    [CallsInProgressAvgDaysDMS]                      FLOAT (53)   NULL,
    [CallsInProgressAvgDaysIDraught]                 FLOAT (53)   NULL,
    [DMSCallsOnHoldBrulinesIssue]                    INT          DEFAULT ((0)) NOT NULL,
    [IDraughtCallsOnHoldBrulinesIssue]               INT          DEFAULT ((0)) NOT NULL,
    [DMSCallsOnHoldClientIssue]                      INT          DEFAULT ((0)) NOT NULL,
    [IDraughtCallsOnHoldClientIssue]                 INT          DEFAULT ((0)) NOT NULL,
    [FlowmetersCleanedDMS]                           INT          DEFAULT ((0)) NOT NULL,
    [FlowmetersCleanedIDraught]                      INT          DEFAULT ((0)) NOT NULL,
    [CallsCancelledDMS]                              INT          DEFAULT ((0)) NOT NULL,
    [CallsCancelledIDraught]                         INT          DEFAULT ((0)) NOT NULL,
    [CallsAbortedDMS]                                INT          DEFAULT ((0)) NOT NULL,
    [CallsAbortedIDraught]                           INT          DEFAULT ((0)) NOT NULL,
    [CalibrationFailureNoProductDMS]                 INT          DEFAULT ((0)) NOT NULL,
    [CalibrationFailureNoProductIDraught]            INT          DEFAULT ((0)) NOT NULL,
    [CalibrationFailureFobbingDMS]                   INT          DEFAULT ((0)) NOT NULL,
    [CalibrationFailureFobbingIDraught]              INT          DEFAULT ((0)) NOT NULL,
    [CalibrationFailureDispenseIssueDMS]             INT          DEFAULT ((0)) NOT NULL,
    [CalibrationFailureDispenseIssueIDraught]        INT          DEFAULT ((0)) NOT NULL,
    [CallsOpenAvgDaysDMS]                            FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CallsOpenAvgDaysIDraught]                       FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenDMS]                           INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsRaisedDMS]                         INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsOutstandingDMS]                    INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsInProgressDMS]                     INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsInProgressAvgDaysDMS]              FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenOutsideSLADMS]                 INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenAvgDaysDMS]                    FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenOutsideSLADMSAvgDays]          FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenIDraught]                      INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsRaisedIDraught]                    INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsOutstandingIDraught]               INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsInProgressIDraught]                INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsInProgressAvgDaysIDraught]         FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenOutsideSLAIDraught]            INT          DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenAvgDaysIDraught]               FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [PriorityCallsOpenOutsideSLAIDraughtAvgDays]     FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [DMSSitesAllInclusive]                           INT          DEFAULT ((0)) NOT NULL,
    [IDraughtSitesAllInclusive]                      INT          DEFAULT ((0)) NOT NULL,
    [DMSSitesPAYGOther]                              INT          DEFAULT ((0)) NOT NULL,
    [IDraughtSitesPAYGOther]                         INT          DEFAULT ((0)) NOT NULL,
    [DMSSitesOver5Years]                             INT          DEFAULT ((0)) NOT NULL,
    [IDraughtSitesOver5Years]                        INT          DEFAULT ((0)) NOT NULL,
    [DMSSitesUnder5Years]                            INT          DEFAULT ((0)) NOT NULL,
    [IDraughtSitesUnder5Years]                       INT          DEFAULT ((0)) NOT NULL
);

