CREATE TABLE [dbo].[Products] (
    [ID]                       INT           IDENTITY (1, 1) NOT NULL,
    [Description]              VARCHAR (50)  NOT NULL,
    [Price]                    MONEY         NULL,
    [Tied]                     BIT           NOT NULL,
    [IsWater]                  BIT           NOT NULL,
    [IsCask]                   BIT           CONSTRAINT [DF_Products_IsCask] DEFAULT (0) NOT NULL,
    [ImageID]                  INT           CONSTRAINT [DF_Products_ImageID] DEFAULT (0) NOT NULL,
    [IconID]                   INT           CONSTRAINT [DF_Products_IconID] DEFAULT (0) NOT NULL,
    [CategoryID]               INT           DEFAULT (1) NOT NULL,
    [TemperatureSpecification] FLOAT (53)    CONSTRAINT [DF_Products_TemperatureSpecification] DEFAULT (6) NOT NULL,
    [TemperatureTolerance]     FLOAT (53)    CONSTRAINT [DF_Products_TemperatureTolerance] DEFAULT (2) NOT NULL,
    [FlowRateSpecification]    FLOAT (53)    CONSTRAINT [DF_Products_FlowRateSpecification] DEFAULT (20) NOT NULL,
    [FlowRateTolerance]        FLOAT (53)    CONSTRAINT [DF_Products_FlowRateTolerance] DEFAULT (2) NOT NULL,
    [IsMetric]                 BIT           DEFAULT (0) NOT NULL,
    [LineCleanDaysBeforeAmber] INT           DEFAULT (8) NOT NULL,
    [LineCleanDaysBeforeRed]   INT           DEFAULT (11) NOT NULL,
    [CreatedBy]                VARCHAR (255) CONSTRAINT [DF_Products_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [CreatedOn]                DATETIME      CONSTRAINT [DF_Products_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [OwnerID]                  INT           DEFAULT (1) NOT NULL,
    [MixRatio]                 FLOAT (53)    DEFAULT (0) NOT NULL,
    [GlobalID]                 INT           DEFAULT (0) NOT NULL,
    [DistributorID]            INT           CONSTRAINT [DF_Products_DistributorID] DEFAULT (1) NOT NULL,
    [Purchasable]              BIT           CONSTRAINT [DF_Products_Purchasable] DEFAULT ((1)) NOT NULL,
    [IncludeInLowVolume]       BIT           DEFAULT ((1)) NOT NULL,
    [IsGuestAle]               BIT           DEFAULT ((0)) NOT NULL,
    [OperationalPrice]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RetailPrice]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Products_ProductCategories] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[ProductCategories] ([ID]),
    CONSTRAINT [FK_Products_ProductOwners] FOREIGN KEY ([OwnerID]) REFERENCES [dbo].[ProductOwners] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [UX_Products_Description] UNIQUE NONCLUSTERED ([Description] ASC) WITH (FILLFACTOR = 90)
);

