CREATE TABLE [dbo].[SiteRankingCurrent] (
    [EDISID]                 INT      NOT NULL,
    [PouringYield]           INT      CONSTRAINT [DF_SiteRankingCurrent_PouringYield] DEFAULT (6) NULL,
    [TillYield]              INT      CONSTRAINT [DF_SiteRankingCurrent_TillYield] DEFAULT (6) NULL,
    [Cleaning]               INT      CONSTRAINT [DF_SiteRankingCurrent_Cleaning] DEFAULT (6) NULL,
    [Audit]                  INT      CONSTRAINT [DF_SiteRankingCurrent_Audit] DEFAULT (6) NULL,
    [TemperatureTL]          INT      NULL,
    [EquipmentRecircTL]      INT      NULL,
    [EquipmentAmbientTL]     INT      NULL,
    [ThroughputTL]           INT      NULL,
    [CleaningTL]             INT      DEFAULT ((6)) NULL,
    [PouringYieldTL]         INT      DEFAULT ((6)) NULL,
    [TillYieldTL]            INT      DEFAULT ((6)) NULL,
    [SiteEquipmentAmbientTL] INT      NULL,
    [SiteEquipmentRecircTL]  INT      NULL,
    [SiteCleaningTL]         INT      NULL,
    [SiteCleaningKegTL]      INT      NULL,
    [SiteCleaningCaskTL]     INT      NULL,
    [SiteThroughputTL]       INT      NULL,
    [SiteThroughputKegTL]    INT      NULL,
    [SiteThroughputCaskTL]   INT      NULL,
    [SiteTemperatureTL]      INT      NULL,
    [SiteTemperatureKegTL]   INT      NULL,
    [SiteTemperatureCaskTL]  INT      NULL,
    [SitePouringYieldTL]     INT      NULL,
    [SitePouringYieldKegTL]  INT      NULL,
    [SitePouringYieldCaskTL] INT      NULL,
    [SiteTillYieldTL]        INT      NULL,
    [SiteTillYieldKegTL]     INT      NULL,
    [SiteTillYieldCaskTL]    INT      NULL,
    [LastUpdated]            DATETIME NULL,
    CONSTRAINT [PK_SiteRankingCurrent] PRIMARY KEY CLUSTERED ([EDISID] ASC)
);

